### ISSUE TITLE
missing 1 required positional argument: 'observation_space'

### ISSUE THREAD

**Issue by Isaac009** [kngwyu/mujoco-maze#15]
>>> import gym
>>> import mujoco_maze
>>> env = gym.make("Ant4Rooms-v0")
/home/user/python_envs/HESS_ENV/lib/python3.8/site-packages/gym/envs/registration.py:555: UserWarning: WARN: The environment Ant4Rooms-v0 is out of date. You should consider upgrading to version `v2`.
  logger.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "home/user/python_envs/HESS_ENV/lib/python3.8/site-packages/gym/envs/registration.py", line 652, in make
    raise e
  File "/home/user/python_envs/HESS_ENV/lib/python3.8/site-packages/gym/envs/registration.py", line 640, in make
    env = env_creator(**_kwargs)
  File "/home/user/Documents/research/RL/PBCS/mujoco-maze/mujoco_maze/maze_env.py", line 216, in __init__
    self.wrapped_env = model_cls(file_path=file_path, **kwargs)
  File "/home/user/Documents/research/RL/PBCS/mujoco-maze/mujoco_maze/ant.py", line 54, in __init__
    super().__init__(file_path, 5)
  File "/home/user/Documents/research/RL/PBCS/mujoco-maze/mujoco_maze/agent_model.py", line 19, in __init__
    MujocoEnv.__init__(self, file_path, frame_skip)
TypeError: __init__() missing 1 required positional argument: 'observation_space'

**Comment by marko-zaric** [comment]
Has this been solved? I encounter the same problem
